/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pikachu;

/**
 *
 * @author laptop
 */
public class Level extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Level.class.getName());

    /**
     * Creates new form Level
     */
    public Level() {
        setContentPane(new backGround_main());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        easyButton = new javax.swing.JButton();
        normalButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        exitButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        easyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        easyButton.setText("DỄ");
        easyButton.setPreferredSize(new java.awt.Dimension(220, 30));
        getContentPane().add(easyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 50));

        normalButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        normalButton.setText("THƯỜNG");
        normalButton.setPreferredSize(new java.awt.Dimension(220, 30));
        normalButton.addActionListener(this::normalButtonActionPerformed);
        getContentPane().add(normalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 50));

        hardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hardButton.setText("KHÓ");
        hardButton.setPreferredSize(new java.awt.Dimension(220, 30));
        getContentPane().add(hardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, 50));

        exitButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton3.setText("<");
        exitButton3.addActionListener(this::exitButton3ActionPerformed);
        getContentPane().add(exitButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("AFICA");
        jButton1.setPreferredSize(new java.awt.Dimension(220, 50));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 220, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("ASIAN ");
        jButton2.setPreferredSize(new java.awt.Dimension(220, 50));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 220, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("EUROPE  ");
        jButton3.setPreferredSize(new java.awt.Dimension(220, 50));
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 220, -1));

        setBounds(0, 0, 814, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void normalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalButtonActionPerformed

    private void exitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton3ActionPerformed
        // TODO add your handling code here:
        PikachuMenu pika = new PikachuMenu();
        pika.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Level().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyButton;
    private javax.swing.JButton exitButton3;
    private javax.swing.JButton hardButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton normalButton;
    // End of variables declaration//GEN-END:variables
}
