/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pikachu;

/**
 *
 * @author laptop
 */
public class setting extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(setting.class.getName());

    /**
     * Creates new form setting
     */
    public setting() {
        setContentPane(new backGround_main());
        initComponents();
System.out.println(getContentPane().getWidth() + " " + getContentPane().getHeight());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        instructionButton1 = new javax.swing.JButton();
        exitmenuButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        volumnButton = new javax.swing.JToggleButton();
        soundButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 54)); // NOI18N
        jLabel2.setText(" CÀI ĐẶT");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(17, 254, 0, 296);
        getContentPane().add(jLabel2, gridBagConstraints);

        nextButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nextButton.setText("CHƠI TIẾP");
        nextButton.setPreferredSize(new java.awt.Dimension(250, 40));
        nextButton.addActionListener(this::nextButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(137, 254, 0, 296);
        getContentPane().add(nextButton, gridBagConstraints);

        newButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newButton.setText("VÁN MỚI");
        newButton.setPreferredSize(new java.awt.Dimension(250, 40));
        newButton.addActionListener(this::newButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 254, 0, 296);
        getContentPane().add(newButton, gridBagConstraints);

        instructionButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instructionButton1.setText("HƯỚNG DẪN");
        instructionButton1.setPreferredSize(new java.awt.Dimension(250, 40));
        instructionButton1.addActionListener(this::instructionButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 254, 0, 296);
        getContentPane().add(instructionButton1, gridBagConstraints);

        exitmenuButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitmenuButton.setText("MÀN HÌNH CHÍNH");
        exitmenuButton.setPreferredSize(new java.awt.Dimension(250, 40));
        exitmenuButton.addActionListener(this::exitmenuButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 254, 0, 296);
        getContentPane().add(exitmenuButton, gridBagConstraints);

        jSplitPane1.setDividerLocation(123);
        jSplitPane1.setDividerSize(4);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(250, 40));

        volumnButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        volumnButton.setText("🎧");
        volumnButton.setPreferredSize(new java.awt.Dimension(125, 40));
        volumnButton.setRolloverEnabled(false);
        volumnButton.addActionListener(this::volumnButtonActionPerformed);
        jSplitPane1.setRightComponent(volumnButton);

        soundButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        soundButton.setText("🔊");
        soundButton.setMaximumSize(new java.awt.Dimension(125, 40));
        soundButton.setPreferredSize(new java.awt.Dimension(125, 40));
        soundButton.setRolloverEnabled(false);
        soundButton.addActionListener(this::soundButtonActionPerformed);
        jSplitPane1.setLeftComponent(soundButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(6, 254, 167, 296);
        getContentPane().add(jSplitPane1, gridBagConstraints);

        setBounds(0, 0, 814, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void volumnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumnButtonActionPerformed
        // TODO add your handling code here:
        if(volumnButton.isSelected()){
        volumnButton.setText("🚫🎧");
    }else{
        volumnButton.setText("🎧");
    }
    }//GEN-LAST:event_volumnButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:    
        this.setVisible(false);             
    }//GEN-LAST:event_nextButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        main Main = new main();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newButtonActionPerformed

    private void exitmenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuButtonActionPerformed
        // TODO add your handling code here:
        PikachuMenu pika = new PikachuMenu();
        pika.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitmenuButtonActionPerformed

    private void instructionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionButton1ActionPerformed
        // TODO add your handling code here:
        instruction_on_main instruct = new instruction_on_main();
        instruct.setVisible(true);        
        this.setVisible(false);
    }//GEN-LAST:event_instructionButton1ActionPerformed

    private void soundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundButtonActionPerformed
        // TODO add your handling code here:                                          
    if(soundButton.isSelected()){
        soundButton.setText("🔇");
    }else{
        soundButton.setText("🔊");
    }
    }//GEN-LAST:event_soundButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new setting().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitmenuButton;
    private javax.swing.JButton instructionButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JToggleButton soundButton;
    private javax.swing.JToggleButton volumnButton;
    // End of variables declaration//GEN-END:variables
}
