/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pikachu_master.User_Interface.Screens;

import com.mycompany.pikachu_master.User_Interface.Components.BackgroundMain;
import com.mycompany.pikachu_master.User_Interface.Components.BackgroundStartScreen;

/**
 *
 * @author laptop
 */
public class MainScreen extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());

    /**
     * Creates new form main
     */
    public MainScreen() {
//        setContentPane(new BackgroundStartScreen());
//        initComponents();

        setContentPane(new BackgroundMain());
            initComponents();

            // Khởi tạo bàn cờ
            PlayScreen gameBoard = new PlayScreen();

            // SỬA TẠI ĐÂY: Thay vì BorderLayout, hãy dùng AbsoluteConstraints
            // Tham số: (x, y, width, height) - Điều chỉnh số này để khớp với ảnh nền của em
            this.getContentPane().add(gameBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 700, 450));

            this.revalidate();
            this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingmainButton = new javax.swing.JButton();
        levelLabel = new javax.swing.JLabel();
        level_point = new javax.swing.JLabel();
        PointLabel = new javax.swing.JLabel();
        point = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Timeline = new javax.swing.JSlider();
        swapButton = new javax.swing.JButton();
        timeButton = new javax.swing.JButton();
        hintButton = new javax.swing.JButton();
        coin = new javax.swing.JLabel();
        coinLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingmainButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        settingmainButton.setText("⚙");
        settingmainButton.setAlignmentY(0.0F);
        settingmainButton.setPreferredSize(new java.awt.Dimension(45, 45));
        settingmainButton.addActionListener(this::settingmainButtonActionPerformed);
        getContentPane().add(settingmainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 40, 30));

        levelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        levelLabel.setText("CẤP ĐỘ:");
        getContentPane().add(levelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        level_point.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        level_point.setText("12");
        getContentPane().add(level_point, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 20));

        PointLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PointLabel.setText("ĐIỂM:");
        getContentPane().add(PointLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        point.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        point.setText("110");
        getContentPane().add(point, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, 10));

        Timeline.setBackground(new java.awt.Color(204, 204, 204));
        Timeline.setToolTipText("");
        Timeline.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(Timeline, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 260, 20));

        swapButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        swapButton.setText("🔁");
        swapButton.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(swapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        timeButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        timeButton.setPreferredSize(new java.awt.Dimension(30, 30));
        timeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeButtonMouseClicked(evt);
            }
        });
        timeButton.addActionListener(this::timeButtonActionPerformed);
        getContentPane().add(timeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        hintButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        hintButton.setText("🔍");
        hintButton.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(hintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        coin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coin.setText("VÀNG:");
        getContentPane().add(coin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        coinLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coinLabel.setText("9999");
        getContentPane().add(coinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 260, 20));

        setSize(new java.awt.Dimension(814, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void settingmainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingmainButtonActionPerformed
        // TODO add your handling code here:
        Pause Setting = new Pause();
        Setting.setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_settingmainButtonActionPerformed

    private void timeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeButtonActionPerformed

    private void timeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_timeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PointLabel;
    private javax.swing.JSlider Timeline;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinLabel;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel level_point;
    private javax.swing.JLabel point;
    private javax.swing.JButton settingmainButton;
    private javax.swing.JButton swapButton;
    private javax.swing.JButton timeButton;
    // End of variables declaration//GEN-END:variables
}
